// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pava
SEXP pava(SEXP R_d1, SEXP R_d2, SEXP R_x);
RcppExport SEXP _icsp2_pava(SEXP R_d1SEXP, SEXP R_d2SEXP, SEXP R_xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_d1(R_d1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_d2(R_d2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_x(R_xSEXP);
    rcpp_result_gen = Rcpp::wrap(pava(R_d1, R_d2, R_x));
    return rcpp_result_gen;
END_RCPP
}
// fastNumericInsert_cpp
SEXP fastNumericInsert_cpp(SEXP newVals, SEXP target, SEXP indices);
RcppExport SEXP _icsp2_fastNumericInsert_cpp(SEXP newValsSEXP, SEXP targetSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type newVals(newValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target(targetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fastNumericInsert_cpp(newVals, target, indices));
    return rcpp_result_gen;
END_RCPP
}
// ic_sp_ch
SEXP ic_sp_ch(SEXP Rlind, SEXP Rrind, SEXP Rcovars, SEXP fitType, SEXP R_w, SEXP R_strata, SEXP R_use_GD, SEXP R_maxiter, SEXP R_baselineUpdates, SEXP R_useFullHess, SEXP R_updateCovars, SEXP R_initialRegVals, SEXP R_derivMethod);
RcppExport SEXP _icsp2_ic_sp_ch(SEXP RlindSEXP, SEXP RrindSEXP, SEXP RcovarsSEXP, SEXP fitTypeSEXP, SEXP R_wSEXP, SEXP R_strataSEXP, SEXP R_use_GDSEXP, SEXP R_maxiterSEXP, SEXP R_baselineUpdatesSEXP, SEXP R_useFullHessSEXP, SEXP R_updateCovarsSEXP, SEXP R_initialRegValsSEXP, SEXP R_derivMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Rlind(RlindSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Rrind(RrindSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Rcovars(RcovarsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fitType(fitTypeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_w(R_wSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_strata(R_strataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_use_GD(R_use_GDSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_maxiter(R_maxiterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_baselineUpdates(R_baselineUpdatesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_useFullHess(R_useFullHessSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_updateCovars(R_updateCovarsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_initialRegVals(R_initialRegValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_derivMethod(R_derivMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(ic_sp_ch(Rlind, Rrind, Rcovars, fitType, R_w, R_strata, R_use_GD, R_maxiter, R_baselineUpdates, R_useFullHess, R_updateCovars, R_initialRegVals, R_derivMethod));
    return rcpp_result_gen;
END_RCPP
}
// findMI
SEXP findMI(SEXP R_AllVals, SEXP isL, SEXP isR, SEXP lVals, SEXP rVals);
RcppExport SEXP _icsp2_findMI(SEXP R_AllValsSEXP, SEXP isLSEXP, SEXP isRSEXP, SEXP lValsSEXP, SEXP rValsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_AllVals(R_AllValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type isL(isLSEXP);
    Rcpp::traits::input_parameter< SEXP >::type isR(isRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lVals(lValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rVals(rValsSEXP);
    rcpp_result_gen = Rcpp::wrap(findMI(R_AllVals, isL, isR, lVals, rVals));
    return rcpp_result_gen;
END_RCPP
}
// s_regTrans
SEXP s_regTrans(SEXP times, SEXP etas, SEXP bli, SEXP regType, SEXP baseType);
RcppExport SEXP _icsp2_s_regTrans(SEXP timesSEXP, SEXP etasSEXP, SEXP bliSEXP, SEXP regTypeSEXP, SEXP baseTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type times(timesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type etas(etasSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bli(bliSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regType(regTypeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type baseType(baseTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(s_regTrans(times, etas, bli, regType, baseType));
    return rcpp_result_gen;
END_RCPP
}
// q_regTrans
SEXP q_regTrans(SEXP p, SEXP etas, SEXP bli, SEXP regType, SEXP baseType);
RcppExport SEXP _icsp2_q_regTrans(SEXP pSEXP, SEXP etasSEXP, SEXP bliSEXP, SEXP regTypeSEXP, SEXP baseTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< SEXP >::type etas(etasSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bli(bliSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regType(regTypeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type baseType(baseTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(q_regTrans(p, etas, bli, regType, baseType));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_icsp2_pava", (DL_FUNC) &_icsp2_pava, 3},
    {"_icsp2_fastNumericInsert_cpp", (DL_FUNC) &_icsp2_fastNumericInsert_cpp, 3},
    {"_icsp2_ic_sp_ch", (DL_FUNC) &_icsp2_ic_sp_ch, 13},
    {"_icsp2_findMI", (DL_FUNC) &_icsp2_findMI, 5},
    {"_icsp2_s_regTrans", (DL_FUNC) &_icsp2_s_regTrans, 5},
    {"_icsp2_q_regTrans", (DL_FUNC) &_icsp2_q_regTrans, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_icsp2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
