// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pava
SEXP pava(SEXP R_d1, SEXP R_d2, SEXP R_x);
RcppExport SEXP _icsp2_pava(SEXP R_d1SEXP, SEXP R_d2SEXP, SEXP R_xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_d1(R_d1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_d2(R_d2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_x(R_xSEXP);
    rcpp_result_gen = Rcpp::wrap(pava(R_d1, R_d2, R_x));
    return rcpp_result_gen;
END_RCPP
}
// fastNumericInsert_cpp
SEXP fastNumericInsert_cpp(SEXP newVals, SEXP target, SEXP indices);
RcppExport SEXP _icsp2_fastNumericInsert_cpp(SEXP newValsSEXP, SEXP targetSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type newVals(newValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target(targetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fastNumericInsert_cpp(newVals, target, indices));
    return rcpp_result_gen;
END_RCPP
}
// hly_sample
List hly_sample(NumericMatrix S_ij, NumericVector left_times, IntegerVector group_var_s, int H);
RcppExport SEXP _icsp2_hly_sample(SEXP S_ijSEXP, SEXP left_timesSEXP, SEXP group_var_sSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type S_ij(S_ijSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type left_times(left_timesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_var_s(group_var_sSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(hly_sample(S_ij, left_times, group_var_s, H));
    return rcpp_result_gen;
END_RCPP
}
// fast_logrank
List fast_logrank(NumericVector time, IntegerVector event, IntegerVector group);
RcppExport SEXP _icsp2_fast_logrank(SEXP timeSEXP, SEXP eventSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_logrank(time, event, group));
    return rcpp_result_gen;
END_RCPP
}
// ic_sp_ch
SEXP ic_sp_ch(SEXP Rlind, SEXP Rrind, SEXP Rcovars, SEXP fitType, SEXP R_w, SEXP R_strata, SEXP R_use_GD, SEXP R_maxiter, SEXP R_baselineUpdates, SEXP R_useFullHess, SEXP R_updateCovars, SEXP R_initialRegVals, SEXP R_derivMethod, SEXP R_baselineStart, SEXP R_profileCI_diff);
RcppExport SEXP _icsp2_ic_sp_ch(SEXP RlindSEXP, SEXP RrindSEXP, SEXP RcovarsSEXP, SEXP fitTypeSEXP, SEXP R_wSEXP, SEXP R_strataSEXP, SEXP R_use_GDSEXP, SEXP R_maxiterSEXP, SEXP R_baselineUpdatesSEXP, SEXP R_useFullHessSEXP, SEXP R_updateCovarsSEXP, SEXP R_initialRegValsSEXP, SEXP R_derivMethodSEXP, SEXP R_baselineStartSEXP, SEXP R_profileCI_diffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Rlind(RlindSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Rrind(RrindSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Rcovars(RcovarsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fitType(fitTypeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_w(R_wSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_strata(R_strataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_use_GD(R_use_GDSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_maxiter(R_maxiterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_baselineUpdates(R_baselineUpdatesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_useFullHess(R_useFullHessSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_updateCovars(R_updateCovarsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_initialRegVals(R_initialRegValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_derivMethod(R_derivMethodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_baselineStart(R_baselineStartSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_profileCI_diff(R_profileCI_diffSEXP);
    rcpp_result_gen = Rcpp::wrap(ic_sp_ch(Rlind, Rrind, Rcovars, fitType, R_w, R_strata, R_use_GD, R_maxiter, R_baselineUpdates, R_useFullHess, R_updateCovars, R_initialRegVals, R_derivMethod, R_baselineStart, R_profileCI_diff));
    return rcpp_result_gen;
END_RCPP
}
// findMI
SEXP findMI(SEXP R_AllVals, SEXP isL, SEXP isR, SEXP lVals, SEXP rVals);
RcppExport SEXP _icsp2_findMI(SEXP R_AllValsSEXP, SEXP isLSEXP, SEXP isRSEXP, SEXP lValsSEXP, SEXP rValsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_AllVals(R_AllValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type isL(isLSEXP);
    Rcpp::traits::input_parameter< SEXP >::type isR(isRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lVals(lValsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rVals(rValsSEXP);
    rcpp_result_gen = Rcpp::wrap(findMI(R_AllVals, isL, isR, lVals, rVals));
    return rcpp_result_gen;
END_RCPP
}
// omp_threads_available
int omp_threads_available();
RcppExport SEXP _icsp2_omp_threads_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(omp_threads_available());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_icsp2_pava", (DL_FUNC) &_icsp2_pava, 3},
    {"_icsp2_fastNumericInsert_cpp", (DL_FUNC) &_icsp2_fastNumericInsert_cpp, 3},
    {"_icsp2_hly_sample", (DL_FUNC) &_icsp2_hly_sample, 4},
    {"_icsp2_fast_logrank", (DL_FUNC) &_icsp2_fast_logrank, 3},
    {"_icsp2_ic_sp_ch", (DL_FUNC) &_icsp2_ic_sp_ch, 15},
    {"_icsp2_findMI", (DL_FUNC) &_icsp2_findMI, 5},
    {"_icsp2_omp_threads_available", (DL_FUNC) &_icsp2_omp_threads_available, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_icsp2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
