# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hly_sample <- function(S_ij, left_times, group_var_s, H) {
    .Call(`_icsp2_hly_sample`, S_ij, left_times, group_var_s, H)
}

fast_logrank <- function(time, event, group) {
    .Call(`_icsp2_fast_logrank`, time, event, group)
}

ic_sp_ch <- function(Rlind, Rrind, Rcovars, fitType, R_w, R_strata, R_use_GD, R_maxiter, R_baselineUpdates, R_useFullHess, R_updateCovars, R_initialRegVals, R_derivMethod, R_baselineStart, R_profileCI_diff) {
    .Call(`_icsp2_ic_sp_ch`, Rlind, Rrind, Rcovars, fitType, R_w, R_strata, R_use_GD, R_maxiter, R_baselineUpdates, R_useFullHess, R_updateCovars, R_initialRegVals, R_derivMethod, R_baselineStart, R_profileCI_diff)
}

findMI <- function(R_AllVals, isL, isR, lVals, rVals) {
    .Call(`_icsp2_findMI`, R_AllVals, isL, isR, lVals, rVals)
}

